comments

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -48,9 +48,9 @@ jobs:
         #  java -cp FileAutomation/target/test-classes com.telus.Properties.ExcelReader
       - name: Run ExcelReader main class
         run: |
-          mvn dependency:build-classpath -Dmdep.outputFile=FileAutomation/classpath.txt -f FileAutomation/pom.xml
-          if [ ! -f FileAutomation/classpath.txt ]; then echo "Classpath file not found!"; exit 1; fi
-          CP=$(cat FileAutomation/classpath.txt):FileAutomation/target/test-classes
+          mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt -f FileAutomation/pom.xml
+          if [ ! -f classpath.txt ]; then echo "Classpath file not found!"; exit 1; fi
+          CP=$(cat classpath.txt):FileAutomation/target/test-classes
           java -cp "$CP" com.telus.Properties.ExcelReader
 
 
